# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ManyToManyField(related_name='comments', to='wall.User'),
        ),
    ]
