# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.date(2018, 7, 17)),
        ),
    ]
